services:
  catalog-service-application:
    container_name: catalog-service-application
    image:  goafabric/catalog-batch-service-quarkus:1.0.2
    restart: 'no'
    ports:
      - "50600:8080"

    command: "-Xmx32m"

    healthcheck:
      test: "curl -f http://localhost:8080/actuator/health || exit 1"
      disable: true #disabled for native images because of no curl
      interval: 5s
      timeout: 10s
      retries: 5

    volumes:
      - tmp_catalog:/tmp
      - applogs_catalog:/usr/share/logs
    networks:
      - ${_Values_root_name}-net
    environment:
      #application
      TZ: Europe/Berlin
      quarkus.http.port: "8080"
      quarkus.http.io-threads: "20"

      #tracing
      quarkus.otel.exporter.otlp.traces.endpoint: "http://host.docker.internal:4317"
      quarkus.application.name: "catalog-service"

      #persistence
      quarkus.datasource.jdbc.url: "jdbc:postgresql://postgres:5432/core"
      #spring.datasource.hikari.maximum-pool-size: "10"
      #spring.datasource.hikari.connection-timeout: "10000"

      database.provisioning.goals: "-import-catalog-data"

      #secrets
      quarkus.datasource.username: "core-service"
      quarkus.datasource.password: "core-service"

      #log levels
      logging.level.root: "WARN"
      logging.level.org.goafabric: "INFO"
      logging.level.org.springframework: "INFO"

    depends_on:
      postgres:
        condition: service_healthy